/*
 * FundRequest model
 * Structure to be used to deserialize requests to /fund api
 *
 *
 * API version: 1.0.0
 * Contact: daniel.maruani@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package rest

import (
	"time"
)

type FundRequest struct {
	Id string `json:"id"`

	CustomerId string `json:"customer_id"`

	LoadAmount string `json:"load_amount"`

	Time time.Time `json:"time"`
}
