/*
 * FundResponse model
 * To be used to as response for funding operation, serialized as json from /fund api
 *
 * API version: 1.0.0
 * Contact: daniel.maruani@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package rest

type FundResponse struct {
	Id string `json:"id"`

	CustomerId string `json:"customer_id"`

	Accepted bool `json:"accepted"`
}
